apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: t1vq9m78c-nodejs 
  janus-idp.io/tekton: t1vq9m78c-nodejs
  backstage.io/kubernetes-id: t1vq9m78c-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: t1vq9m78c-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml