apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t1vq9m78c-nodejs-gitops
  description: This is GitOps manifest for t1vq9m78c-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=t1vq9m78c-nodejs
    backstage.io/kubernetes-id: t1vq9m78c-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t1vq9m78c-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t1vq9m78c-nodejs
